version: '2'
services:
  web:
    image: php:7.1.11-apache
    container_name: php
    restart: always
    ports:
    - "8000:80"
    - "8443:443"
    volumes:
     - /webdev/attribute-grabber:/var/www/html 
  # MYSQL
  mysqldb:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_HOST: localhost
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: attribute-grabber
    restart: always
  myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb